### ISSUE TITLE
how to skip scenario using hook

### ISSUE THREAD

**Issue by secilkaplan** [Arthy000/gherkin-testcafe#106]
Hi, this is more of a question.. 
I want some of my scenarios to still show in the report with Skipped tag.  My goal is to tag them with for example @Skip and in certain conditions defined in Before hook skip running the whole steps of the scenario but still show the name in my report.

I tried using TestCafe's test.skip function which did not work. I'm only able to manipulate the status by doing `t.testRun.test.skip = true`

Also I found below docs for how to skip a cucumber test with the hooks. Could you help me how to make this happen with gherkin-testcafe or is it even possible?

https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/hooks.md#skipping-in-a-before-hook
https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/step_definitions.md

**Comment by Arthy000** [comment]
Hi @secilkaplan,

Skipping tests programatically (from the hooks for instance) has been asked many time to TestCafe's developers. Until now, to the extend of my knowledge, it hasn't been done.
The only way to skip a test is to access the test object and use the skip method (and that's not great because hardcoded), but gherkin-testcafe doesn't expose the test object in the first place because of how it was designed.

You may find some of your needs are met by using [tags](https://github.com/Arthy000/gherkin-testcafe#tags) to include or exclude scenarios (it's basically another way to filter tests)

Another possibility is to include your whole test functions in a `if` statement, then set the condition to fail in the hook :/

**Comment by secilkaplan** [comment]
Hi @Arthy000 , thank you for the information and ideas.
