### ISSUE TITLE
Running with specific browser

### ISSUE THREAD

**Issue by kel666** [Arthy000/gherkin-testcafe#112]
Hi

I'm trying to run gherkin-testcafe with a specific executable, like this:

`npx gherkin-testcafe --skip-js-errors --compiler-options typescript.options.esModuleInterop=true "chromium:headless;path=d:\chromium\chrome.exe" -r gtc-reporter-spec,junit:gherkinReport.xml src/e2etest/**/*.ts src/e2etest/**/*.feature`

tried also different quotes combinations and without browser alias, only path, but always get this:

`ERROR Cannot find the browser. "chromium:headless;path=d:\chromium\chrome.exe" is neither a known browser alias, nor a path to an executable file.
`

Is browser path supported?

tnx
Fabio

**Comment by Arthy000** [comment]
Hi Fabio,

I'm not sure what is wrong with your command, but on my side I can start a specific browser with the path argument.

Regarding the feature itself, GTC has nothing to do with it, it simply forwards the argument to TC itself, so the first thing is to try the same argument but with `npx testcafe` instead of `npx gherkin-testcafe`
If it starts correctly with TC then there is an issue on GTC's side, but honestly I'd be surprised, because as I said all that's done in GTC is fowarding the browser argument to TC's argument parser.

If you do manage to start the browser with TC but not with GTC, then the first thing I'll need will be your TC and GTC versions

**Comment by kel666** [comment]
Tnx for the quick reply.

Anyway, I don't need anymore to use specific browser so I will close the issue.

But tnx again for the fast feedback!
Fabio
