### ISSUE TITLE
Question / feature request

### ISSUE THREAD

**Issue by tmaslen** [Arthy000/gherkin-testcafe#12]
Hiya,

This project is awesome! Thanks for building it.

Is it possible to get gherkin-testcafe to output a list of pending step definitions if they don't exist already?

Thanks,
Tom.

**Comment by Arthy000** [comment]
Hello,

Thanks :D I have to admit that at the moment I haven't done much since I inherited the project, aside from answering questions, but I appreciate :p 

At the moment, not really. You'll get an error for each scenario missing at least one step, but you can only see that by running all the tests, and even then you'll only see the first step missing for each scenario.

Personally, I use VSC with an addon named [Cucumber (Gherkin) Full Support](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete) which, once properly configured, will highlight the steps without implementation in your feature file.

I'd be willing to implement that feature if you want.

**Comment by Arthy000** [comment]
I'll give your request a try, I'll reopen if I decide to do it :)

**Comment by Arthy000** [comment]
Hello again, I just finished implementing the feature :D 
I'll review my code in a few days to make sure it's not too bad, in the mean time you can test the branch linked to this issue :)
