### ISSUE TITLE
Scenario Outline is not working with v5.6.0

### ISSUE THREAD

**Issue by suchit29** [Arthy000/gherkin-testcafe#122]
While running it says step implementation is missing

Feature: login 
Scenario Outline: login to HRM 
Given I open the page
When I enter <username> and <password>
Then I should see login page 
|username|password| 
|admin|admin123| 

Step Definition -
When("I enter {string} and {string}", async (t, username, password) => {
await t.typeText(input(#uname), username)
.typeText(input(#pword), password):
});

**Comment by Arthy000** [comment]
Hi @suchit29, 

First of all, you should use 3 backticks (`) when copying code ([see here](https://www.markdownguide.org/extended-syntax/#syntax-highlighting))
```gherkin
Scenario Outline: login to HRM
  Given I open the page
  When I enter <username> and <password>
  Then I should see login page
  |username|password|
  |admin|admin123|
```
Makes it way easier to read for me :)

I can tell you right away that there is an issue in your feature file, you are missing the `Examples` keyword. Without it the outline will not work.

The correct syntax is
```gherkin
Scenario Outline: login to HRM
  Given I open the page
  When I enter <username> and <password>
  Then I should see login page

  Examples:
    | username | password |
    | admin    | admin123 |
```

You can see the correct syntax in one of [these examples](https://github.com/Arthy000/gherkin-testcafe/blob/master/examples/google.feature)

Also, idk if you used the CLI or the API, but in both cases make sure you specify both the feature and the step implementation files in the source argument.

I hope this solves your issue, otherwise I'd be glad to help.
