### ISSUE TITLE
Doc is missing solution for an invalid installation

### ISSUE THREAD

**Issue by behzad1993** [Arthy000/gherkin-testcafe#128]
Hi, 

i just started a new project with your package and got always the error message from your [doc](https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations).

After a day i figured out, that i need to delete the node_modules which is globally installed, because for some reasons it was cucumber was installed there. 

Adding this, just as a hint would help i think #80 

Best, Behzad

**Comment by Arthy000** [comment]
Hi @behzad1993 

The link you provided is *not* my doc, it's Cucumber's, and it does explicitely state that cucumber should not be installed globally.
(furthermore, [*my* doc](https://github.com/Arthy000/gherkin-testcafe#installation) actually gives you the command line to install Cucumber locally, as it should be)

Regarding the ticket you referenced, it has been closed for a year, I'm not sure what the point was.

It doesn't really feel like something I can fix. Sure I could add a warning in my documentation that people should install Cucumber globally, but what happens if the Cucumber team changes that later? I get misleading documentation. 

I'm not closing the ticket yet so if there is anything else you need help with, don't hesitate.
