### ISSUE TITLE
[QUESTION] JSON Reporter

### ISSUE THREAD

**Issue by divichub** [Arthy000/gherkin-testcafe#144]
Hi,

do you plan to add JSON reporter to the list of already adapted reporters like `gtc-reporter-spec`? I'm running testcafe with gherkin inside Jenkins and this particular Jenkins plugin only works with `json` files.

I'm using this reporter for now https://github.com/hdorgeval/testcafe-reporter-cucumber-json but it's not supported on new versions of testcafe.

**Comment by Arthy000** [comment]
Hello @divichub,

There is no plan to adapt the existing JSON reporter from TestCafe because it already contains everything needed to handle errors in Gherkin scenarios:

Here is an example:
```json
{
  "name": "Feature: Name",
  "path": "path/to/file.feature",
  "meta": {
    // feature meta
  },
  "tests": [
    {
      "name": "Scenario: Scenario name",
      "meta": {
        "tags": "",
        "steps": [
          // list of steps in order
          {
            "type": "Context",
            "prefix": "Background",
            "keyword": "Given ",
            "text": "I opened Google's search page"
          },
        ],
        "failIndex": 1 // the failing step, absent/undefined if success (0 based)
      },
      "errs": [
            ... // empty if success, otherwise contains what you should display
      ],
      // other testrun data
    }
  ]
}
```

Everything you need is in the meta part of any given test:
- all the steps, their types, their content, and so on (regardless of success) in scenario order
- the failing step index (if applicable)
Additionally, you can use the errs property of the test to describe whatever went wrong.

To use it, just set the reporter to "json"
Using the CLI:
```cli
gherkin-testcafe (insert your usual configuration) --reporter json:output.json
```
or using the API:
```ts
runner
  // insert your usual configuration
  .reporter("json:output.json")
```

I don't see anything to improve here. However if you have a specific usecase I'd be happy to help.
