### ISSUE TITLE
[Question]multiple browser windows support --experimental-multiple-windows

### ISSUE THREAD

**Issue by rydzsmigly** [Arthy000/gherkin-testcafe#156]
Hi,
I have a question about running tests with CLI options.
Testcafe introduced in 3.5.0 new CLI flag --experimental-multiple-windows to support multiple browser windows testing.

I have gherkin-testcafe 7.2.0 verion and testcafe 3.5.0.
I'm using in my runner:
const testCafeInterface = require('gherkin-testcafe'); 

How should pass this option to enable this flag? 

I tried : "node myRunner.js  --tags=<my tags> --experimental-multiple-windows" and it's not working.

**Comment by Arthy000** [comment]
Hi @rydzsmigly,

To use the CLI flag, as per [testcafe's documentation](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-multiple-windows):
```sh
gherkin-testcafe chrome my-tests --experimental-multiple-windows
```
However, you implemented your own runner, and you are thus using the API, not the CLI, and that option is not available since it's only there as a preliminary fix.

**Comment by rydzsmigly** [comment]
Hi @Arthy000 ,

Thank you for the explanation! I need to wait for the final fix then.
