### ISSUE TITLE
Add a way to configure the underlying fixture

### ISSUE THREAD

**Issue by sgarfinkel** [Arthy000/gherkin-testcafe#23]
The main use-case here is injecting [client scripts](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/inject-client-scripts.html#add-client-scripts-to-specific-tests) into the running page, which can only be done at the fixture level.

It would also allow users to configure the page used for the entire scenario via the `fixture().page()` function.

**Comment by Arthy000** [comment]
The only way I see to do this is to use a [configuration file](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html)

Though I haven't tested it yet. I'll make sure it works and if it doesn't I'll try to fix it.

**Comment by sgarfinkel** [comment]
That does work, however it limits what you can and can't configure. Having direct access to the fixture via a callback is definitely preferable.

**Comment by Arthy000** [comment]
Okay so I looked it up a bit, and it seems that _at best_ this will be difficult and tricky.
The reason is that this package overwrites a function (getTests) from the original TestCafe package, and in that function the fixtures are generated on the fly.
The return value of getTests will then be internally used by TestCafe so I can't access it, it's too late.

The only idea I have is to add a new API method that would allow you to set fixture parameters, but not the way you wanted:
```js
runner.setFixtureParameter(fixtureName, parameterName, value)
```

And if you think that solution is acceptable, it is going to take a while to implement, otherwise sadly I'll have to give this issue the same treatment as [that one](https://github.com/kiwigrid/gherkin-testcafe/issues/46)

**Comment by khanh-shady** [comment]
Hi all, I too ran into this problem and configuration file did wonder for me. But TestCafe needed to be upgraded to newest version (@v1.10.2-alpha.1) and they removed the [tsConfigPath](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#tsconfigpath) function in favour of [compilerOptions](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#compileroptions), also they specify TypeScript option to pass into their TypeScript compiler. 

Do you think you can make an upgrade for this? Thanks!

**Comment by Arthy000** [comment]
Hello khanh-shady,
I think this request deserves its own issue :)

**Comment by sgarfinkel** [comment]
@khanh-shady Definitely a different issue, however for me it does seem that the `.testcaferc.json` is being respected by the runner.

@Arthy000 Alternatively could you expose the underlying `test`? You can also inject client scripts that way.

**Comment by Arthy000** [comment]
Exposing the test poses the exact same issues as exposing the fixture, sadly, because they are both generated on the fly [here](https://github.com/Arthy000/gherkin-testcafe/blob/develop/src/compiler.js#L154)

Again, I'm not saying it is not possible (though it would require a lot of work) but I'm also not sure it is :( 

The fact that the former maintainer of this package said it was not possible does not really give me confidence :(

**Comment by thelazurite-cell** [comment]
There may be two ways of working around this, I haven't tested the second.
1. Like you say you can add it to your testcaferc file, or you could do this programmatically before you start your testruns: `runner.clientScripts([{ path: path.join(__dirname, './your-client-script.js') }]);`
2. Within your compiler class, set the t.ctx to contain your fixture and try setting your client script through that method.

**Comment by thelazurite-cell** [comment]
> 2. Within your compiler class, set the t.ctx to contain your fixture and try setting your client script through that method.

So i've had a bit of a play around with this idea, and I've got it sending the context to the BeforeAll hook... unfortunately it doesn't appear to execute the client script I've provided unfortunately.

**Comment by Arthy000** [comment]
Hello @thelazurite-cell

Thanks for your help. While the first idea only partially works (doesn't give access to the page() method of the fixture for instance), you may onto something with your second idea.
I'll try a few things and comment here.

**Comment by thelazurite-cell** [comment]
Hello again @Arthy000 
I think I may have another possible solution to this problem, I wonder what your opinion of this may be. In my fork of the framework, it relies more on it being more config driven than passing through information from the CLI. This does have it's benefits. As an example, I can configure a tag to state whether it should be ignored or run:

```json
{
  "testConfiguration": [
    {
      "tag": "VerboseTests",
      "shouldRun": true,
      "because": "Verbose tests will not be run, but are provided for a technical overview of what steps run"
    },
    {
      "tag": "exampleTag",
      "shouldRun": true
    },
  ]
}
```

possibly, this could be extended:

```json
{
  "tag": "exampleTag",
  "shouldRun": true,
  "metadata": {
    "metaName": "myValue",
    "foo": "bar"
  },
  "clientScripts": [
    "./relative/path/toScript.js"
  ],
  "page": "http://example.com"
}
```

there are some classes to help fetch the information, and then you'd need to map the tag information to the fixture or scenario from the compiler.js

**Comment by thelazurite-cell** [comment]
Hello Again :) 

I've had another idea, this kind of plays off the idea of configuration once more. I am curious what you think about this approach? @Arthy000 @sgarfinkel 

Within my fork of the framework, I have set up some classes, to help pick up and read a json file which contains some information on what tags should run or be ignored, as a downside with the way I have written this the framework becomes a lot more config driven rather than relying on cli arguments.

Here is an example of how one of these files looks:

```json
{
  "testConfiguration": [
    {
      "tag": "runWarmUp",
      "shouldRun": true
    },
    {
      "tag": "exampleTag",
      "shouldRun": true
    },
    {
      "tag": "ignore",
      "shouldRun": false,
      "because": "Tests have been set as ignored."
    }
  ],
  "acceptanceCriteria": {
    "acceptanceCriteriaItems": [
      {
        "tag": "maxUploadSizeInMb",
        "value": "20"
      }
    ]
  }
}
```

You could possibly extend a `testConfigurationItem` to include the extra fields requested within this issue like this:

```json
    {
      "tag": "exampleTag",
      "shouldRun": true,
      "metaData": {
        "foo": "bar"
        "time": "for gin :-)"
      },
      "clientScripts": [
        "./relative/path/to-my-script.js"
      ],
      "page": "http://example.com"
    },
```

you would then need to read this data, and then within your compiler.ts/js before calling the `fixture` or `test`:

* read the tags your `scenario` or `feature` has assigned
* call the helper class to get the configuration for that tag
* on your testcafe js calls, apply the information accordingly.

**Comment by Arthy000** [comment]
Very interesting.

You would still be unable to access the fixture / test in the code, but you can at least tweak their behavior a little.

The trade off is, as you said, that you have to do a lot more work configuration-wise. If you expect the configuration to change often it implies a lot of maintenance (that is my case, so this wouldn't work for me.)

If this can be implemented without breaking the normal behavior of gherkin-testcafe, and @sgarfinkel sees this as an acceptable solution, I'm willing to give it a shot.

**Comment by thelazurite-cell** [comment]
With TestCafe >1.13.x deprecating the `t.setPageLoadTimeout` function, it may also be worth adding a way to configure the timeouts for the feature/scenario this way too should the solution be accepted
