### ISSUE TITLE
On mac, gherkin-testcafe does not work

### ISSUE THREAD

**Issue by yhsiah** [Arthy000/gherkin-testcafe#5]
Tried this on my machine and another person's too.

using `gherkin-testcafe` on the cli with --help or to run tests does not work, and we get back this error:

```
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

it does work with using npx - e.g. `npx gherkin-testcafe --help`

it also works when you specify node and the specific main.js file e.g. `node node_modules/gherkin-testcafe/main.js --help`

**Comment by Arthy000** [comment]
Hello, if you want to use gherkin-testcafe without the npx part, you need to install the package globally (with the -g param)

``` 
npm install -g gherkin-testcafe
```

The documentation here specifies that you should replace "testcafe" with "gherkin-testcafe".
If you check Testcafe's documentation it explicitly states that you need to install the tool globally to use testcafe instead of npx testcafe.

I will improve the documentation so this is clearer.

If you prefer a local installation, then you can either use npx as you did or create your own runner using the API.

I hope this helps :)

**Comment by yhsiah** [comment]
Great thanks, that does help 👍

**Comment by Arthy000** [comment]
I added a line to the readme regarding global installation
