### ISSUE TITLE
Before Hook does not receive TestController as parameter

### ISSUE THREAD

**Issue by csurfleet** [Arthy000/gherkin-testcafe#63]
Hi, I'm using gherkin-testcafe with TypeScript and I'm running into issues with the Before hooks. I was expecting the TestController to be the parameter passed to me, but I instead receive an ITestCaseHookParameter:
![image](https://user-images.githubusercontent.com/1318832/130737437-8a217755-adaf-43e1-8bac-2e3abaf15460.png)

This type is a pure Cucumber type, so there is no way of getting from here to a TestController object, which is what I actually need. Do we know if I'm doing something wrong here to get the incorrect type, or is there a way of getting the TestController without it being passed into the method for me?

**Comment by csurfleet** [comment]
I discovered that I can import the const 't' from TestCafe and use that from my hook without it needing to be passed to me. Is this just a case of updating the readme to reflect this?

**Comment by Arthy000** [comment]
This issue should have been fixed by [this commit](https://github.com/Arthy000/gherkin-testcafe/pull/37/commits/8401669b5f6451932cef91af023d2605781fa766)
Make sure you are using an up-to-date version of the package (version 5.0.1 or higher)

Closing this issue as it received no answer for a while, feel free to reopen it.
