### ISSUE TITLE
[QUESTION] Receive list of files that are going to be executed

### ISSUE THREAD

**Issue by jcroma** [Arthy000/gherkin-testcafe#96]
Hi there!
I'm wondering if there is a possibility to receive list of gherkin files path that are going to be executed ? Just want to update status of them to 3rd party and I catch case when I execute command with only tags

**Comment by Arthy000** [comment]
Hello there!
As of now the closest you can get from the list of gherkin files is using the argument --dry-run (CLI) or the method runner.dryRun() (API).

It will return something like this:
```
% yarn cli --dry-run                                

   Feature: Using custom parameter types
     Steps: 5/5

   Feature: Datatable demo feature
     Steps: 3/3

   Feature: Doc string feature
     Steps: 2/2

   Feature: The big search feature
     Steps: 11/11

   Feature: HTTP Basic Authentication
     Steps: 4/4
```

That's probably not exactly what you want, but hopefully it's close enough.

Otherwise, the easiest option is probably to use the parameter you gave gherkin-testcafe and use OS commands to retreive the list of files.

**Comment by jcroma** [comment]
Well, as you said, I'm going to use regex path for tests that I'm passing to launch tests and search files if they have chosen tag or not :) 
Thanks for response, I'm going to close that issue.
